### PR TITLE
A re-implementation of Deep Biaffine Attention for Neural Dependency …

### PR DESCRIPTION
**Pull request by hankcs**
Hi elit team,

This is a re-implementation of Stanford's "[Deep Biaffine Attention for Neural Dependency Parsing](https://arxiv.org/pdf/1611.01734.pdf)" at ICLR 2017.

This parser has been well tested and documented. More information can be found at [this file](https://github.com/hankcs/elit/blob/ed5e4cf8025b6be487132456143482fd5282e1e1/md/biaffine-parser.md).

Hope this parser can enrich this project. Thanks.

Han He

### CODE REVIEW

**Comment by imgarylai** [comment]
@hankcs Appreciate your pull request! I will review this pull request as soon as I can. Thank you. :)

**Comment by imgarylai** [comment]
Hello @hankcs, I'm reviewing your code, and I want to ask you some questions. 

There is no problem to run your code, all the configurations are clear. However, could you tell me which dataset you have tested? From the GloVe dataset, did you try all four datasets, the pre-trained word vectors? If not, which has been tested? Also, would you please let me know which Conll dataset did you use and the source? It would be great that we can also put dataset source reference in the tutorial. People who are interesting in this project can get into it with lower barrier!

Again, I really appreciate your work!

**Comment by hankcs** [comment]
Sure,

1. I've tested on the [PTB-SD](https://catalog.ldc.upenn.edu/ldc99t42). As PTB is phrase tree structured, user needs to convert it to CoNLL. For resources of the conversion, one can refer to:
   - https://github.com/clulab/processors/wiki/Converting-from-Penn-Treebank-to-Basic-Stanford-Dependencies
   - https://github.com/hankcs/TreebankPreprocessing
   - The samples I sent to your email.
   - The Universal Dependencies contain lines of comments, which are not supported by the preprocessing code yet.
1. The embedding file used is the `glove.6B.100d.txt`. The dimension must match with `word_dims` specified in config file. Users are free to use other embedding files, but be careful about the dimensions.

Please let me know if you have any questions.
Thanks,

Han He

**Comment by imgarylai** [comment]
Thank you. This pull request is merged!

**Pull request merged**
